version: 2.1

jobs:
  build_norns:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: buildroot-downloads
      - restore_cache:
          key: buildroot-ccache
      - run: ./build.sh
      - save_cache:
          key: buildroot-downloads-{{ epoch }}
          paths:
            - ~/.cache/buildroot-downloads
      - save_cache:
          key: buildroot-ccache-{{ epoch }}
          paths:
            - ~/.cache/buildroot-ccache
      - store_artifacts:
          path: ./output/images/norns.img
          destination: norns.img
      - store_artifacts:
          path: ./output/graphs
          destination: graphs/norns
  build_norns_raspberrypi3:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: buildroot-downloads
      - restore_cache:
          key: buildroot-ccache
      - run: ./build.sh norns_raspberrypi3_defconfig
      - save_cache:
          key: buildroot-downloads-{{ epoch }}
          paths:
            - ~/.cache/buildroot-downloads
      - save_cache:
          key: buildroot-ccache-{{ epoch }}
          paths:
            - ~/.cache/buildroot-ccache
      - store_artifacts:
          path: ./output/images/norns-raspberrypi3.img
          destination: norns-raspberrypi3.img
      - store_artifacts:
          path: ./output/graphs
          destination: graphs/raspberrypi3

workflows:
  version: 2
  build:
    jobs:
      - build_norns
      - build_norns_raspberrypi3:
          requires:
            - build_norns
